### ISSUE TITLE
Contact form - doesn't send messages

### ISSUE THREAD

**Issue by noirrak** [CollinDaugherty/grav-theme-prime#1]
Hello! 
The form doesn't send messages. On other themes it works fine.

**Comment by CollinDaugherty** [comment]
I will look into it and get that fixed soon.

**Comment by noirrak** [comment]
@CollinDaugherty, have you had time to look ino this?
Your theme is very clean, I would like to use it :)

**Comment by CollinDaugherty** [comment]
Sorry it took forever to get around to this. The issue should be fixed now.

**Comment by noirrak** [comment]
Hello @CollinDaugherty!
I updated my contact.md. Unfortunately, but:
`message: 'Thank you for getting in touch!'`
This information is not displayed when the user sends a message.

**Comment by CollinDaugherty** [comment]
Does the message send?

What version of Grav are you running and what version is your Form plugin?

**Comment by noirrak** [comment]
Yes, messages are successfully sent.
> What version of Grav are you running and what version is your Form plugin?
v2.13.0 (current).

**Comment by CollinDaugherty** [comment]
So the page reloads but no message is displayed above the form?

I made a new grav installation with the Prime theme and I can't recreate this issue. Can you show me the code in your contact.md?
