### ISSUE TITLE
Error & Problem plugins don't work

### ISSUE THREAD

**Issue by noirrak** [CollinDaugherty/grav-theme-prime#3]
It seems that these plugins do not work.

1. Error plugin should redirect to /error. The current situation looks like this:
![45236](https://user-images.githubusercontent.com/20505787/37256966-a7eae804-2562-11e8-9681-2e1b2b3d24a4.jpg)
+ How to make 404 error use PRIME template?

2. Problem plugins - I can't run it.

**Comment by CollinDaugherty** [comment]
The error page is working as intended. This theme provides no error page styling.

> Problem plugins - I can't run it.

Could you provide more details?
